play_recipe:
  fields:
    device_id:
      required: true
      selector:
        text:
          multiple: true
    recipe_id:
      required: true
      selector:
        text:
save_recipe:
  fields:
    name:
      required: true
      selector:
        text:
    stages:
      required: true
      selector:
        object:
delete_recipe:
  fields:
    name:
      required: true
      selector:
        text:
adjust_timer:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: anova_culinary
          domain: number
    amount:
      required: true
      selector:
        number:
          min: -1440
          max: 1440
          unit_of_measurement: min
